#!/bin/bash
# Title: One Possible variable to be set on the terminal
# Description: When any terminal is open, the prompt will present to you a variable called $PS1 that is responsible for telling you many things like yoyr Username, Host machine name, current directory and if you are currently logged as either root (by displaying #) or as a normal user (by displaying $)
#              This file saves one of the best $PS1 to use at termux
# Use 1: set this variable on ~/.bashrc on at DRYa/all/source-all-drya-files
# Use 2: source this file (because it has a usable variable)

# $PS1 used at Termux
declare PS1='\[\e[0;32m\]\w\[\e[0m\] \[\e[0;97m\]\$\[\e[0m\] '
