#!/bin/bash

# Title: Dv Bash Alias (for Linux)
# Use: This file is meant to be sourced from "~/.bashrc"

# List of all alias
alias ..="cd .."
alias .="ls"
alias ,="cd"
alias update-alias="cd ~/Repositories/DRYa/all/ && vim config-bash-alias"
