#!/bin/bash
# Title: source-all-drya-files
# Place in this file all script you need ~/.bashrc to recognize
# Description: At ~/.bashrc you should place only ONE line to source this file for DRYa, and this file should source all others

# Display the standard welcome termux message
   # Testing with the command 'uname -o' where the output should be "Android" to see if the termux is the terminal running
   # Also sending the error message to /dev/null in case dWiki repository is not yet downloaded side-by-side with DRYa
   if [ $(uname -o) == "Android" ]; then cat ${v_REPOS_CENTER}/dWiki/termux/default-welcome-screen-text 2>/dev/null; fi

# Neofetch is not needed... It is just for fun
   neofetch 2>/dev/null

function f_verbose_start-1 {
   echo "DRYa: file running: ${DRYa_HEART}"
   # echo "Installed at.."
}

# Dependency: figlet
   # Not every instalation of figlet comes witht the same standard font, lets corret that
   alias figlet="figlet -f standard.flf" # My favourite font is called standard.flf ## CAREFULL, this font may be missing

# Repository: ezGIT
   # Define a key to call the entire program
      alias G="bash ${v_REPOS_CENTER}/ezGIT/ezGIT.sh"
      # uDev: for some repos, must run a script that searches for updates at terminal startup

   # Load all alternative git alias:
      source ${v_REPOS_CENTER}/ezGIT/all/etc/config-bash-alias

   #uDev: #bash ezGIT/all/bin/automatic uploader for repos like "omni-log-Dv" that are meant to be ALWAYS in the "cloud" uDev: this script will run at terminal startup and will upload+download a list of file always.
   #uDev: #for messenger-like comunications: download+upload content for a private github repo and after the other mobile phone downloads it, use git to remove it from the git log permanently
   
# Repository: moedaz
   #alias mo="bash ${v_REPOS_CENTER}/moedaz/moedaz.sh" ## Exists inside the file 'source-all-moedaz-files'
   source ${v_REPOS_CENTER}/moedaz/all/source-all-moedaz-files 2>/dev/null
   source ~/.config/h.h/moedaz/terminal-text-color 2>/dev/null

# Repository: QR-walking-stick (inside dWiki/TODO-apps)
   alias qr="bash ${v_REPOS_CENTER}/dWiki/TODO-apps/QR-walking-stick/store-data-from-QRcodeApp.sh"

# Repository: upK
   source /data/data/com.termux/files/home/Repositories/upK/all/bin/bash/time.sh 2>/dev/null

# Repository 112-Shiva-Sutras
   alias ss="bash ${v_REPOS_CENTER}/112-Shiva-Sutras/ss.sh"

# Repository row-reader
   alias rr="bash ${v_REPOS_CENTER}/row-reader/row-reader.sh"

# Repository: DRYa (internal files)
   # Remove temporary dir created by DRYa's other scripts
      rm -rf ~/.tmp/

   # Allow/disable verbose output for DRYa:
      f_verbose_start-1  ##Comment/Uncomment this line to toggle on or off

   # Sourcing DRYa's own configs
      source ${v_REPOS_CENTER}/DRYa/all/etc/config-bash-alias
      alias ,.="vim ${v_REPOS_CENTER}/DRYa/all/etc/config-bash-alias"

   # DRYa executable
      alias drya="bash ${v_REPOS_CENTER}/DRYa/drya.sh"
   
   # Sourcing the temporary/local configs for DRYa (if they ido not exist, send err: /dev/null)) It can store temporary variables for debugging process of some app
      source ~/.config/h.h/drya/.dryarc 2>/dev/null
      source ${v_REPOS_CENTER}/DRYa/all/var/appended-from-dryarc 2>/dev/null

