#!/bin/bash
cut_3_fields_relative_path
function f_greet_alternative {
   echo ' ____  ______   __    '
   echo '|  _ \|  _ \ \ / /_ _ '
   echo '| | | | |_) \ V / _` |'
   echo '| |_| |  _ < | | (_| |'
   echo '|____/|_| \_\|_|\__,_|'
   echo '                      '
}

function f_greet {
   # This script could also ensure the standard.flf font is correctly installed.
      # To find the standard PATH for figlet fonts you could iddue the command '$ figlet -I2'
   figlet DRYa -f standard.flf 2>/dev/null
}

function f_set_installer {
   echo $v_ans
}

function f_exec {
   f_greet || f_greet_alternative
   f_set_installer
}
f_exec




case $1 in 
	-h | -? | help | -help | --help | *) 
	       # Tell the user the current state of the instalation
	       echo hi
	;;
esac

