#!/bin/bash

# Title: 1st stage of DRYa instalation
# Use:
   # 1 - Navigate to the directory where this file is located
      # TO RUN THIS FILE PROPERLY, YOU MUST NAVIGATE TO THE DIR IN WHICH THE SCRIPT IS LOCATED
      # BECAUSE THE SCRIPT IS MEANT TO FIND THE ABSOLUTE PATH IN WHICH YOU ARE
   # 2 - Run this script (which is the first instalation script)  with: '$ bash 1-Run-me-to-enable-DRYa-dir-to-be-moved'
       # 2.1 This script will source the second instalation file  
   

# This variable will decide which menu 'select' will present to the user 
   # Before any change to the installation
   declare DRYa-instalation-state=0

# This variable stores the current location of the installer
   # And manages to cut the last variable to decide in the end what files are needed to be moved
   declare DRYa-instalation-dir=$(pwd)

   # uDev: cut the end part of the var






   First allow bash to know where DRYa is located

only after that you should source the other script
That other script will tell ~/.bashrc where the directory will be installed and will move DRYa there
(it will only move it if first this script is ran and finds out where DRYa is)
