#!/bin/bash

# Title: Insert an entry at ~/.bashrc to load DRYa
# Description: In order for ~/.bashrc not to have duplicate entries, this script relies on the brother script (brother in terms of directory location) to delete any previous entries and only then it pastes a new entry into ~/.bashrc
# Use:

# Not-a-function on purpouse f_greet (in order not to be sourced)
   clear 
   figlet DRYa

# Not-a-function on purpouse f_explain (in order not to be sourced)
   # First determine where to install
      echo "Welcome to DRYa"
      echo " > Don't Repeat Yoursel (app)"
      sleep 0.5
      echo 
      echo "This script running is meant to install DRYa"
      echo " > Please choose one centralized directory"
      echo "   where DRYa and all other Seiva's Software"
      echo "   can be installed (e.g. /home/Repositories)"
      #echo " > You should prefer absolute paths instead of relative paths"
      #echo " > In order go cross platform"
      echo
      sleep 0.5
      echo "Instalation - Step 1 - by sourcing this file:"
      echo " > Issue the command '$ source <name-of-this-file>' and then"
      echo "   travel to the directory you want the software to be installed in"
      echo "   and from there, invoke this script with the command '$ DRYa-install-me-here' " 
      echo 
      sleep 0.5
      echo "Instalation - Step 2 - Move the DRYa repo into the dir you choose"
      echo " > If you were able to source this file, you must have a copy of DRYa"
      echo "   and that copy (this copy) should be moved into the directory in which"
      echo "   you did invoke DRYa-install-me-here"
      echo "   uDev: create a function that automatically moves the directory"
      echo 
      sleep 0.5
      echo "After instalation:"
      echo " > You cat unload the function that was sourced for instalation"
      echo "   you loaded: DRYa-install-me-here that exports the variable \$DRYa_PATH"
      echo "   Now, if the place for instalation is how you like, you can prevent it from changing"
      echo "   by invoking: unset-DRYa-installer"
      echo

function delete-previous-DRYa-installation {
   # Search and delete the entry for DRYa inside ~/.bashrc
      
      # Asking if the user want to create a backup first
         while true
           do
              echo -n " > Do you want a backup to be created from your ~/.bashrc? (y/n) "
              read -n 1 -s v_ans
	      echo

           case $v_ans in
              y | Y)
		 cp ~/.bashrc ~/.bashrc.bak
		 echo "   > file ~/.bashrc copied to ~/.bashrc.bak (ENTER to continue)"
		 read -s -n 1
		 break
	      ;;
              n | N)
	         echo "   > You are choosing not to create a backup"
	         echo "   > Ctrl + C:  to CANCEL, or"
	         echo "   > 3 x ENTER: to CONTINUE"
		 read -s -n 1
		 read -s -n 1
		 read -s -n 1
		 break
	      ;;
              *)
		      echo " > Please choose a valid Option (ENTER to continue)"
		 read -s -n 1
		 echo
	      ;;
	   esac
	done


	
      # Deleting empty lines found only at the bottom of the file 
         # It deletes one by one with a while loop (while the last line is found empty)
         
	 # Using TAIL to print only the last line inside a variable called: last_line
	    last_line=$(tail -n 1 ~/.bashrc )

	 # Creating am empty dir and an empty file for our process to take place
	    mkdir -p ~/.tmp/
	    touch ~/.tmp/tmp
  
	 # If the last function found an empty line, then the next while loop will run until something is found
	    # The meaning of -z is "empty". Therefore is $last_line = -z (empty), then do something
	    while [ -z $last_line ]; do 

	       # Copying the entire file to the file 'tmp' except the last 1 line
               head -n -1 ~/.bashrc > ~/.tmp/tmp

	       # Deleting ~/.bashrc with empty space before restpring it WITHOUT empty space
	       rm ~/.bashrc

	       # Renaming tmp file (with .bashrc contents) to it's real name
	       mv ~/.tmp/tmp ~/.bashrc

	       # Evaluate the file againg to check if there is more empty lines needed to be removed the next loop
	       last_line=$(tail -n 1 ~/.bashrc )
            done

	    echo "Done removing empty lines"
	    read


      # Finding the line containing: "# Load Seiva's main repo (one file that wakes all others)"
         # and deleting also the next 2 lines which are the actual code
         sed -i "/# Load Seiva's main repo (one file that wakes all others)/,+2d" ~/.bashrc
   
}
delete-previous-DRYa-installation

function DRYa-install-me-here {
   # Asking if the user wants the previous DRYa instalation to be removed (if any)
      # This deletes only the 2 lines of code inside ~/.bashrc
      # uDev: Find first if there is any entry at ~/.bashrc to avoid this speach
      echo "DRYa: Do you want this script"
      echo " > to remove the 2 lines of code maybe present inside"
      echo "   ~/.bashrc from a possible previous DRYa instalation?"
      echo "   (ignore if you never installed DRYa before)"
      read -s -n 1 -p " > Remove? (y/n)" v_ans
      
      case $v_ans in
         y | Y)
            delete-previous-DRYa-installation
            echo 
            echo "DRYa: entry removed from ~/.bashrc"
         ;;
         n | N)
            echo
            echo "DRYa: you choose N"
            echo " > Continuing..."
         ;; 
      esac
      
   # Defining the environment variable:
      DRYa_PATH=$(pwd)
      export DRYa_PATH
      echo " > DRYa: Installing at: $DRYa_PATH"
   

   # Pasting a new entry inside ~/.bashrc (these 2 lines are responsible to load every other Seiva's Repositories
      # Pasting 1 empty line + 3 lines of code:
      echo ""                                                          >> ~/.bashrc
      echo "# Load Seiva's main repo (one file that wakes all others)" >> ~/.bashrc
      echo "   DRYa_PATH=$DRYa_PATH; export $DRYa_PATH"                >> ~/.bashrc
      echo "   source ${DRYa_PATH}/DRYa/all/source-all-drya-files"     >> ~/.bashrc

   # Time to move the DRYa directory
      echo 
      echo "DRYa: 2 Lines of code where send from DRYa to ~/.bashrc"
      echo "   > This directory is ready to receive any Seiva's Software"
      echo "   > Now, move DRYa directory to this directory in which you are right now"

   # Remember to unset
      echo 
      echo "You can even unset the installer"
      echo " > Type: unset-DRYa-installer"
}
DRYa-install-me-here

function unset-DRYa-installer {
   unset DRYa-install-me-here
   echo " > DRYa: environment variable \$DRYa_PATH was unset"
}

