#!/bin/bash

# Creating 4 nested while loops to create a menu

# Question 1
   clear
   v_question_1="My question is this..."
   echo $v_question_1
   read -n 1 -s -p "what is your answer? " v_ans
   p1=1
   
   while [ $v_ans != "y" ]; do  # Attemp to use multiple conditions failed # || [ $v_ans != "n" ] || [ $v_ans != "h" ]; do
      clear
      echo "This was asked $p1 times already"
      echo $v_question_1
      read -n 1 -s -p "what is your answer? " v_ans

      read -s -n 1 -t 1
      p1=$((p1+1))
   done
   
   echo "At the end, your answer was $v_ans"
