#!bin/bash
# Title: drya-termux-omni-key

function f_greet {
   clear
   figlet Omni Key
}

v_cetralized_termux_p=${v_REPOS_CENTER}/DRYa/all/etc/dot-files/termux/termux.properties
v_termux_p=~/.termux/termux.properties

# Escape Key para as teclas:
   # F5: \e[15~
   # F6: \e[17~
   # F7: \e[18~

   # Saber mais em: `D wiki` > Informatica > Bssh > Terminal Escape Keys
   
# DRYa-termux-omni-key (Bash keyboard bindings)
   # Bind F7 keycode: "\e[18~"
     v_default_omni_key="ॐ"
   
      # To print "Hi!" (just print, example) 
         #bind '"\e[18~":"Hi!"'

      # To exec 'man cat' 
         #bind -x '"\e[18~":"man cat"'

      # To exec 'upk' 
         function f_set_omni_key_upk {
            cp $v_cetralized_termux_p ~/.termux
            sed -i "s/ॐ/⏚/g" $v_termux_p
            bind -x '"\e[18~":"upk"'
            termux-reload-settings
         }

      # To exec 'luxam' 
         function f_set_omni_key_luxam {
            cp $v_cetralized_termux_p ~/.termux
            sed -i "s/ॐ/✡/g" $v_termux_p
            bind -x '"\e[18~":"luxam"'
            termux-reload-settings
         }

      # To exec 'trade' 
         function f_set_omni_key_trade {
            cp $v_cetralized_termux_p ~/.termux
            #sed -i "s/ॐ/₸/g" $v_termux_p
            sed -i "s/ॐ/ᜎ/g" $v_termux_p

            # Mudar a omni-key principal para o 'T' e definir a sua fx
               #bind -x '"\e[18~":"cd ~/sl/trade"'
               bind -x '"\e[18~":"T"'

            # Mudar a omni-key parcial 'A' para a fx: [Dos conteudos da pasta (a lista de scripts) filtra e apresentar so os scripts que sao para executar, com um comando 'read' a perguntar qual quer executar]
            # Mudar a omni-key parcial 'B' para a fx: [Mudar todas as teclas para apoio ao Tmux]

            termux-reload-settings
         }

      # To exec 'admin' 
         function f_set_omni_key_admin {
            echo "Admin Home not ready yet"
         }

      # To open/exec the Android App: "Leitor QR"
         function f_set_omni_key_qr {
            cp $v_cetralized_termux_p ~/.termux
            sed -i "s/ॐ/⎆/g" $v_termux_p
            bind -x '"\e[18~":"am start --user 0 -a andrppoid.intent.action.MAIN -n com.teacapps.barcodescanner/net.qrbot.ui.main.MainActivity"'
            termux-reload-settings
         }
      
      #bind -x '"\e[18~":"f_set_omni_key_qr"'



      function f_reset_omni_key {
         # Reset omni-key 

         cp $v_cetralized_termux_p ~/.termux
         #sed -i "s/⎆/ॐ/g" $v_termux_p       ## Se o ficheiro em .../etc/dot-files/... for copiado diretamente para ~/.termux/termux.properties entao nao é preciso 'sed'
         termux-reload-settings 2>/dev/null  ## Won't work on WSL2
         bind -x '"\e[18~": f_my_reset_test'

      }
      #f_reset_omni_key  ## Esta Fx faz reset durante o startup do terminal por engano






########################################################################
# Bug fix to STDIN on interactive drya-omni-key using Bash 'bind -x'
# source: https://stackoverflow.com/questions/65465973/bind-interactive-command-to-a-key-sequence

stty_orig=$(stty -g)

function f_my_reset_test {
  local stty_bkup=$(stty -g)
  stty "$stty_orig"

  # Function WE want to run here:
     f_key
     #f_key_fzf  # uDev: After begug this fx, replace f_key for this

  stty "$stty_bkup"
}

bind -x '"\e[18~": f_my_reset_test'


##########################################################################











function f_key {
   # Menu para alternar drya-termux-omni-key icon e funcionalidade
   #
   # Bug: Quando em bash é usado o "F7 bind -x to key" entao encrava as funcoes bash que tiverem 'read -p "resposta? " v_ans'

   clear
   figlet Omni Key  # uDev: criar failsafe

   echo "Escolha nova funcao para o botao Omni-Key (Termux):"
   echo "----------------------------------------------------"
   echo " | 1 | Omni-Key   | (reset)"
   echo " | 2 | UPK        | "
   echo " | 3 | QR         | "
   echo " | 4 | Luxam File | "
   echo " | 5 | Trade      | " 
   echo " | 6 | Jarve      | (Domotica)"
   echo " | 7 | Messenger  | "
   echo " | 8 | + Layouts  | "
   echo "----------------------------------------------------"
   read -n 1 -p "   < " v_ans

   if   [ $v_ans == "1" ]; then echo && f_reset_omni_key
   elif [ $v_ans == "2" ]; then echo && f_set_omni_key_upk
   elif [ $v_ans == "3" ]; then echo && f_set_omni_key_qr
   elif [ $v_ans == "4" ]; then echo && f_set_omni_key_luxam
   elif [ $v_ans == "5" ]; then echo && f_set_omni_key_trade
   elif [ $v_ans == "6" ]; then echo && f_set_omni_key_admin
   fi

   echo

}


function f_key_fzf {
   # Menu Simples

   # Lista de opcoes para o menu `fzf`
      Lz3="DRYa Termux Omni Key"; Lz4=$v_drya_fzf_menu_hist

      L9="9. + Layouts para Termux Keys"
      L8="8. Messenger"
      L7="7. Jarve (Palacio Manager)"
      L6="6. Trade Directory"
      L5="5. Luxam File"
      L4="4. QR"
      L3="3. UPK"
      L2="2. OM"
      L1='1. Cancel'

      L0="SELECIONE 1 do menu: "
      
      v_list=$(echo -e "$L1 \n$L2 \n$L3 \n$L4 \n$L5 \n$L6 \n$L7 \n$L8 \n$L9 \n$L10 \n\n$Lz3" | fzf --cycle --prompt="$L0")

   # Perceber qual foi a escolha da lista
      [[ $v_list =~ $Lz3  ]] && echo "$Lz2" && history -s "$Lz2"
      [[ $v_list =~ "9. " ]] && echo
      [[ $v_list =~ "8. " ]] && echo
      [[ $v_list =~ "7. " ]] && f_set_omni_key_admin
      [[ $v_list =~ "6. " ]] && f_set_omni_key_trade
      [[ $v_list =~ "5. " ]] && f_set_omni_key_luxam
      [[ $v_list =~ "4. " ]] && f_set_omni_key_qr
      [[ $v_list =~ "3. " ]] && f_set_omni_key_upk
      [[ $v_list =~ "2. " ]] && echo "OM" && f_reset_omni_key
      [[ $v_list =~ "1. " ]] && echo "Canceled: $Lz2" && history -s "$Lz2"
      unset v_list
    
}
