#!/bib/bash
 
#alias mk="mkdir -p" # Creates one directory for each name given as an argument and in case that succeeds, changes working directory for the directory given as the first argument
 #uDev: `mk .` to go to last created dir
 #uDev: `mk dir1 . dir2 dir3` to make all dirs and navigate do dir2




# Sourcing DRYa Lib 1: Color schemes
   v_lib1=${v_REPOS_CENTER}/DRYa/all/lib/libs/drya-lib-1-colors-greets.sh
   source $v_lib1 2>/dev/null || (read -s -n 1 -p "DRYa libs: $__name__: drya-lib-1 does not exist (error)" && echo )

   v_greet="DRYa"
   v_talk="DRYa: mk: "

   # Examples: `db` (an fx to use during debug)
   #           f_greet, f_greet2, f_talk, f_done, f_anyK, f_Hline, f_horizlina, f_verticline, etc... [From the repo at: "https://github.com/SeivaDArve/DRYa.git"]





function mk {

   if [[ -z $* ]]; then
      f_talk; echo "mk: Instructions"
              echo ' > `mk`                   : Show these instructions'
              echo ' > `mk <dir>`             : Automatically create <dir> && cd <dir>'
              echo ' > `mk <dir> <dir> <...>` : Automatically create all dirs'
              echo ' > If `fzf` is installed, will ask to which dir to navigate'

   elif [ $1 == "." ]; then
      shift

      if [[ -z $* ]]; then
        f_talk; echo "No args remaining"

      else
         f_talk; echo "vao ser criadas todas as pastas fornecidas como args"

         # uDev: o arg '.' pode ser adicionado DEPOIS da pasta para a qual se quer navegar. assim o '.' pode ser o ultimo argumento

         #
         # Notas: Como funciona esta detecao de argumentos:
         #     $#       devolve o número total de argumentos.
         #     ${!#}    usa indireção, ou seja, devolve o valor do argumento cujo número é $#.
         #     Exemplo: se $# for 4, ${!#} = ${4}.)
         #


         for i in $@
         do
            mkdir -p $*
         done
      fi


   else 
      # All arguments will be converted into new directories
      
      for i in $*
      do
         mkdir -p $i
      done
   fi
}
