#!/bin/bash
# Title: logout-all-drya-files
# Description: file that runs all functions from every app before shell logs out

clear
figlet DRYa

echo "DRYa: Restoring files and configs before terminal exit"

# Create a separation line to distinguish changes easier
   f_hzl
   echo $v_line

# Restoring termux touch keybord to omni-key's default key
   cp ${v_REPOS_CENTER}/DRYa/all/etc/dot-files/termux/termux.properties ~/.termux/ && echo " > Omni-key default key: restored"

# Time to allow the user to read
   sleep 2
